---
title: "WP4_phy_1a_create_regionlist_Baltic"
author: "Markus Lindh"
date: '2020-09-28'
output: html_document
---

# Global options

```{r global_options}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
require(sf)
```

Remember to create folders "raw_data" and "derived_data"!

# Geographic search and view layers
marineregions ids can be used.
They live in the layer MarineRegions:eez_iho
intersection eez and iho regions

View layers

```{r viewlayers}
layerurl <- "http://geo.vliz.be/geoserver/MarineRegions/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=MarineRegions:eez_iho_union_v2&outputFormat=application/json"
# download layer as spatial sf object
regions <- sf::st_read(layerurl)
st_crs()

coi <- c("Sweden", "Denmark", "Norway", "Russia", "Germany",
                   "Finland", "Lithuania", "Poland", "Estonia", "Latvia")
# Filtered region below looses class sf of data because of st_drop_geometry() and just data.frame remains which st_bbox cannot interpret below, why drop? I added sf_drop_geometry below before saving file to .csv
baltic <- regions %>%
  # sf::st_drop_geometry()%>% 
   filter(country %in% coi) %>% 
   filter(iho_sea %in% c("Baltic Sea", "Gulf of Bothnia", "Gulf of Finland", "Gulf of Riga", "Kattegat", "Skaggerak"))

baltic %>% filter(mrgid %in% baltic$mrgid) %>%
  ggplot() +
  geom_sf(fill = "blue") +
  geom_sf(data = regions, fill = "transparent", color = "white") +
  geom_sf_text(aes(label = mrgid), size = 2.5) +
  coord_sf(st_bbox(baltic)[c(1,3)], st_bbox(baltic)[c(2,4)], expand = T)
ggsave("data/derived_data/regionsOfInterest_preliminary.png", width = 3, height =  4, )
```

# Save layer to file

```{r savelayers}
baltic %>% st_drop_geometry() %>%
 write_delim("data/derived_data/baltic_regions.csv", delim = ";") # "baltic_regions.csv" is the file to use for the next step
```

## Reproducibility

```{r reproducibility}
# Date time
Sys.time()

# Here we store the session info for this script
sessioninfo::session_info()
```