---
title: "WP4_phy_3_Baltic_final_prod.Rmd"
author: "Luuk van der Heijden, modified by Markus Lindh"
date: "15 june 2020, modified 2020-09-28"
output: html_document
---

# Global options

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
require(sf)
```

# We now have the dataset we want to work with. These datasets, however, some things still have to be adjusted. 

```{r datasetPreparation}
# Load the fix_phy.Rdata that was created for the specific location
load(file.path("data/derived_data/fix_phy.Rdata"))

# 1. Seasons have to be added so that we can use them later. 
# 2. Occurrence has to numerical
# 3. Column with species names has to be extracted from scientificnameaccepted

temp_phy <- fix_phy %>%
  mutate(season = case_when(
    month %in% 3:5 ~ "spring",
    month %in% 6:8 ~ "summer",
    month %in% 9:11 ~ "autumn",
    month %in% 1:2 ~ "winter",
    month %in% 12 ~ "winter")) %>%                                                        # 1. Seasons were added
  mutate(occurrence = 1) %>%                                                              # 2. Occurrence added
  separate(scientificnameaccepted, c("genus_new", "species"), " ", remove = FALSE) %>%    # 3. Species name added
  select(-genus_new)

sum(is.na(temp_phy$season))

# 4. Coordinates have to be changed (from WGS84 to UTM)
phy <- temp_phy %>% 
  st_as_sf(coords = c('decimallongitude', 'decimallatitude'), crs = 4326) %>%  # This was the old coordinate code
  st_transform(crs = 32631) %>%                                                # This is the new coordinate code used
  mutate(xUTM = st_coordinates(.)[,1],                                         # We then extract them and assign them
         yUTM = st_coordinates(.)[,2]) %>%                                     # to x and y columns
  st_drop_geometry()                                                           # and drop the old geometry column
```

# Finally, we remove the duplicates that originated from two datasets and create the final product that can be plotted

```{r datasetFinalPreparation}
# Create two datasets, one for species and one for genus level
# Species datasets (for which we drop the genus levels only)
phy_sp <- phy %>%
  filter(!species %in% NA) %>%
  distinct(aphiaid, datasetID, scientificnameaccepted, date, eventid, xUTM, yUTM, year, season, occurrence, .keep_all = TRUE) 

# Genus datasets
phy_gen <- phy %>%
   distinct(genus, datasetID, date, xUTM, yUTM, .keep_all = TRUE) # Here we remove the duplicates that originated due to focusing on genera alone
# This is something to keep in mind, when plotting the maps and figures.
# Save phy files
save(phy_sp, file = "data/derived_data/phy_sp.Rdata")
save(phy_gen, file = "data/derived_data/phy_gen.Rdata")
```

## Reproducibility

```{r reproducibility}
# Date time
Sys.time()

# Here we store the session info for this script
sessioninfo::session_info()
```
